# Pure Python vs. Numpy - Lab

## Introduction 

Numpy, Scipy, and Pandas provide a significant increase in computational efficiency with complex mathematical operations as compared to Python's built-in arithmetic functions. In this lab, you will calculate and compare the processing speed required for calculating a dot product using both basic arithmetic operations in Python and Numpy's `.dot()` method. 

## Objectives
You will be able to:

- Compare the performance of high-dimensional matrix operations in Numpy vs. pure Python

## Problem 

Write a routine to calculate the dot product between two $200 \times 200$ dimensional matrices using:

a) Pure Python (no libraries)

b) Numpy's `.dot()` method 


### Create two $200 \times 200$ matrices in Python and fill them with random values using `np.random.rand()` 

In [15]:
# Compare 200x200 matrix-matrix multiplication speed
import numpy as np

In [16]:
# Set up the variables
A = np.random.rand(200, 200)
B = np.random.rand(200, 200)

In [19]:
A[:5, :5]

array([[0.29240053, 0.45196423, 0.70330086, 0.64395759, 0.35786479],
       [0.81967049, 0.09548897, 0.58210304, 0.6199452 , 0.46703499],
       [0.08600536, 0.14232086, 0.51910329, 0.95827259, 0.22599615],
       [0.59153542, 0.34782914, 0.75469262, 0.33702977, 0.97773176],
       [0.03137763, 0.15773792, 0.07006973, 0.97546025, 0.37243989]])

In [20]:
B[:5, :5]

array([[0.73870009, 0.00602642, 0.95509827, 0.85760662, 0.14815763],
       [0.06865005, 0.08624991, 0.52025095, 0.78818274, 0.4950172 ],
       [0.84661703, 0.51696223, 0.05832268, 0.92421699, 0.31909184],
       [0.49908778, 0.8933921 , 0.39349868, 0.88568674, 0.80003423],
       [0.10472219, 0.50097153, 0.28814431, 0.25397989, 0.60847143]])

## Pure Python

* Initialize a zeros-filled `numpy` matrix
* In Python, calculate the dot product using the formula 


$$ \large C_{i,j}= \sum_k A_{i,k}B_{k,j}$$


* Use Python's `timeit` library to calculate the processing time
* [Visit this link](https://www.pythoncentral.io/time-a-python-function/) for an in-depth explanation on how to time a function or routine in Python

**Hint**: Use a nested `for` loop for accessing, calculating, and storing each scalar value in the resulting matrix. 

In [17]:
import timeit

C = np.zeros((200, 200))

def dotprod(mat1, mat2):
    for i in range(mat1.shape[0]):
        for j in range(mat2.shape[1]):
            val = 0
            for k in range(mat1.shape[1]):
                val += mat1[i, k] * mat2[k, j]
            C[i, j] = val
            
# Start the timer
start = timeit.time.time()

dotprod(A, B)

end = timeit.time.time()
# Matrix multiplication in pure Python


time_spent = end - start

print('Pure Python time:', time_spent, 'sec.')

Pure Python time: 4.047186851501465 sec.


In [18]:
C[:5, :5]

array([[53.01467117, 51.57097373, 51.35739335, 54.23592162, 47.92381651],
       [48.89191109, 46.95459388, 47.23269117, 49.72174185, 45.10483649],
       [51.74930099, 52.52590308, 51.61727106, 55.50363648, 47.68998865],
       [50.0048762 , 51.64685748, 48.91744247, 54.57791932, 46.12138043],
       [52.4565229 , 52.24601037, 50.35034598, 56.23688849, 48.83350931]])

## Numpy 
Set the timer and calculate the time taken by the `.dot()` method for multiplying $A$ and $B$ 


In [22]:
# Start the timer
start = timeit.time.time()

# Matrix multiplication in numpy
D = A.dot(B)

end = timeit.time.time()

time_spent = end - start
print('Numpy time:', time_spent, 'sec.')

Numpy time: 0.0009691715240478516 sec.


In [23]:
# We can see that the results are the same, in a very small fraction of the time.
D[:5, :5]

array([[53.01467117, 51.57097373, 51.35739335, 54.23592162, 47.92381651],
       [48.89191109, 46.95459388, 47.23269117, 49.72174185, 45.10483649],
       [51.74930099, 52.52590308, 51.61727106, 55.50363648, 47.68998865],
       [50.0048762 , 51.64685748, 48.91744247, 54.57791932, 46.12138043],
       [52.4565229 , 52.24601037, 50.35034598, 56.23688849, 48.83350931]])

### Your comments

In [24]:
# Lets see what fraction of the time it took, rounding to the nearest thousandth of a sec
.001 / 4.047

0.00024709661477637757

In [ ]:
# It took .02% of the time to use numpy vs pure python

## Summary

In this lab, you performed a quick comparison between calculating a dot product in Numpy vs pure Python. You saw that Numpy is computationally much more efficient than pure Python code because of the sophisticated implementation of Numpy source code. You're encouraged to always perform time tests to fully appreciate the use of an additional library in Python. 